version: '3.7'

services:
  soceton:
    container_name: soceton_world_frontend
    tty: true
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './:/soceton-world-frontend'
      - './node_modules:/soceton-world-frontend/node_modules'
    ports:
      - '3002:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true

